### ISSUE TITLE
Bitbucket script doesn't work

### ISSUE THREAD

**Issue by Melzar** [solanolabs/solano_plugins#5]
Hello,

Looks like bitbucket script doesn't work. Still getting permission denied with error 126 on solano. Another thing is that if you enter via debug mode and try to run script manually then I'm receiving error on line 24 like '(' unexpected character.

Is there some special configuration on solano to have it working correctly?

**Comment by IsaacChapman** [comment]
I expect the error 126 may be a auth issue with bitbucket. 

The difference between the behavior in a normal build and a debug console may be due to the bash interpreter. Can you try either removing the `()` characters on line 24 (or `function`, but not both) in a debug console? Adding a `set -x` should provide more detailed output.
